specVersion: 0.2.0
name: moonbeam-subquery
version: 0.0.4
description: >-
  This SubQuery project can be use as a starting point for Moonbeam alpha
  network
repository: 'https://github.com/subquery/moonbeam-alpha-subql-starter'
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://moonbeam.api.onfinality.io/public-ws'
  genesisHash: '0xfe58ea77779b7abda7da4ec526d14db9b1e9cd40a217c34892af80a9b332b76d'
  dictionary: 'https://api.subquery.network/sq/subquery/moonbeam-dictionary'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: parachainStaking
            method: Rewarded
       
